name = "family-sync"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "FAMILY_GROUPS"
id = "106bbafd50b045fdae143b114d94c014"
preview_id = "a8a951ee4e67422c9975901455ac9b1a"

[vars]
ALLOWED_ORIGINS = "https://shelter-route.pages.dev,http://localhost:5174"

[env.dev.vars]
ALLOWED_ORIGINS = "http://localhost:5173,http://localhost:5174,http://localhost:4173,http://127.0.0.1:4174"

[env.production.vars]
ALLOWED_ORIGINS = "https://shelter-route.pages.dev"
